services:
    profile_bundle.user_profile.manipulator:
        class: MMC\Profile\Component\Manipulator\UserProfileManipulator
        arguments:
            - '%mmc_profile.profile_class%'
            - '%mmc_profile.userProfile_class%'

    profile_bundle.user_profile.securizing_manipulator:
        class: MMC\Profile\Component\Manipulator\SecurizingUserProfileManipulator
        arguments:
            - "@profile_bundle.user_profile.manipulator"
            - '@security.authorization_checker'

    profile_bundle.profile_type.validator:
        class: MMC\Profile\Component\Validator\ProfileTypeValidator
        arguments:
            - '@profile_bundle.profile_type.provider'

    profile_bundle.profile_type.provider:
        class: MMC\Profile\Component\Provider\ProfileTypeProvider

    profile_bundle.profile_controller:
        class: MMC\Profile\Bundle\ProfileBundle\Controller\ProfileController
        arguments:
            - '@templating'
            - "@security.token_storage"
            - "@profile_bundle.user_profile.securizing_manipulator"
            - "@profile_bundle.user_profile.manager"
            - "@profile_bundle.user.manager"
            - '@form.factory'
            - '@router'
            - '@profile_bundle.ramsey_uuid_generator'
            - '@profile_bundle.profile_type.validator'
            - '%mmc_profile.profile_class%'

    profile_bundle.default_controller:
        class: MMC\Profile\Bundle\ProfileBundle\Controller\DefaultController
        arguments:
            - '@templating'
            - "@security.token_storage"
            - "@profile_bundle.user.manager"

    profile_bundle.profile.manager:
        class: MMC\Profile\Component\Manager\ProfileManager
        arguments:
            - '@doctrine.orm.entity_manager'

    profile_bundle.user.manager:
        class: MMC\Profile\Component\Manager\UserManager
        arguments:
            - '@doctrine.orm.entity_manager'
            - '%mmc_profile.user_class%'

    profile_bundle.user_profile.manager:
        class: MMC\Profile\Component\Manager\UserProfileManager
        arguments:
            - '@doctrine.orm.entity_manager'

    profile_bundle.ramsey_uuid_generator:
        class: MMC\Profile\Component\UuidGenerator\RamseyUuidGenerator

    profile_bundle.profile_type.create:
        class: MMC\Profile\Bundle\ProfileBundle\Form\ProfileType
        arguments: ["@profile_bundle.profile_type.provider"]
        tags:
            - { name: form.type }

# VOTERS

    profile_bundle.security.voter.edit_user_profile:
        class: MMC\Profile\Component\Security\Voter\EditUserProfileVoter
        tags:
            - { name: security.voter }

    profile_bundle.security.voter.edit_profile:
        class: MMC\Profile\Component\Security\Voter\EditProfileVoter
        tags:
            - { name: security.voter }

    profile_bundle.security.voter.edit_user:
        class: MMC\Profile\Component\Security\Voter\EditUserVoter
        tags:
            - { name: security.voter }
