services:
    profile_bundle.user_profile.manipulator:
        class: MMC\Profile\Component\Manipulator\UserProfileManipulator
        arguments:
          - 'AppBundle\Entity\Profile'
          - 'AppBundle\Entity\UserProfile'

    profile_bundle.profile_type.validator:
        class: MMC\Profile\Component\Validator\ProfileTypeValidator
        arguments:
          - '@profile_bundle.profile_type.provider'

    profile_bundle.profile_type.provider:
        class: MMC\Profile\Component\Provider\ProfileTypeProvider

    profile_bundle.profile_controller:
        class: MMC\Profile\Bundle\ProfileBundle\Controller\ProfileController
        arguments:
            - '@templating'
            - "@security.token_storage"
            - "@profile_bundle.user_profile.manipulator"
            - "@doctrine.orm.entity_manager"
            - '@form.factory'
            - '@router'