services:
    profile_bundle.user_profile.manipulator:
        class: MMC\Profile\Component\Manipulator\UserProfileManipulator
        arguments:
          - 'AppBundle\Entity\Profile'
          - 'AppBundle\Entity\UserProfile'

    profile_bundle.profile_type.validator:
        class: MMC\Profile\Component\Validator\ProfileTypeValidator
        arguments:
          - '@profile_bundle.profile_type.provider'

    profile_bundle.profile_type.provider:
        class: MMC\Profile\Component\Provider\ProfileTypeProvider

    profile_bundle.profile_controller:
        class: MMC\Profile\Bundle\ProfileBundle\Controller\ProfileController
        arguments:
            - '@templating'
            - "@security.token_storage"
            - "@profile_bundle.user_profile.manipulator"
            - "@profile_bundle.user_profile.manager"
            - '@form.factory'
            - '@router'
            - '@profile_bundle.ramsey_uuid_generator'
            - 'AppBundle\Entity\Profile'

    profile_bundle.profile.manager:
        class: MMC\Profile\Component\Manager\ProfileManager
        arguments:
          - '@doctrine.orm.entity_manager'

    profile_bundle.user.manager:
        class: MMC\Profile\Component\Manager\UserManager
        arguments:
          - '@doctrine.orm.entity_manager'

    profile_bundle.user_profile.manager:
        class: MMC\Profile\Component\Manager\UserProfileManager
        arguments:
          - '@doctrine.orm.entity_manager'

    profile_bundle.ramsey_uuid_generator:
        class: MMC\Profile\Component\UuidGenerator\RamseyUuidGenerator
