services:
    profile_bundle.user_profile.manipulator:
        class: MMC\Profile\Component\Manipulator\UserProfileManipulator

    profile_bundle.profile_type.validator:
        class: MMC\Profile\Component\Validator\ProfileTypeValidator
        arguments:
          - '@profile_bundle.profile_type.provider'

    profile_bundle.profile_type.provider:
        class: MMC\Profile\Component\Provider\ProfileTypeProvider
